### ISSUE TITLE
机器人不进群阿巴阿巴

### ISSUE THREAD

**Issue by daoguang1012** [hx-w/CSGOWiki-Plugins#11]
![image](https://user-images.githubusercontent.com/62734528/109296712-be089780-786b-11eb-82b6-52a52dd20b77.png)

**Comment by hx-w** [comment]
我上小号同意了，如果还有问题请联系我


| |
Herixth
|
|
17361019875@163.com
|
签名由网易邮箱大师定制
在2021年2月26日 19:49，daoguang1012<notifications@github.com> 写道：

**Comment by hx-w** [comment]
群人数较多时机器人不会自动进群，出现这种情况暂时联系我，我手动添加。后续会更新加群方式

**Comment by H0wAway** [comment]
可以close了
