### ISSUE TITLE
游戏内发送!qq 机器人群里会发生乱码

### ISSUE THREAD

**Issue by anyongye** [hx-w/CSGOWiki-Plugins#12]
游戏内:永夜‎ ： !qq 测试
机器人在QQ群:[ÍõÀÚSB] æ°¸å¤: æµè¯

**Comment by hx-w** [comment]
@bot 状态， 得到的反馈也是乱码吗

**Comment by anyongye** [comment]
反馈里中文的服务器名字会是乱码，但是玩家名字不是






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hx-w/CSGOWiki-Plugins"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月28日(星期天) 下午4:36
收件人:&nbsp;"hx-w/CSGOWiki-Plugins"<CSGOWiki-Plugins@noreply.github.com&gt;;
抄送:&nbsp;"3090874781"<3090874781@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [hx-w/CSGOWiki-Plugins] 游戏内发送!qq 机器人群里会发生乱码 (#12)





 
@bot 状态， 得到的反馈也是乱码吗

**Comment by hx-w** [comment]
关于qq里显示乱码的问题，我刚刚区别的服务器测了一下，也使用了中文+英文的名称，是正常显示的。
也有其他用户是用的中文名，同样可以正常显示。
所以我猜想可能和你服务器上装的其他插件有关，建议换英文名尝试一下。
如果不介意的话 可以发一下服务器装有插件的列表

**Comment by anyongye** [comment]
QQ发你插件列表



---原始邮件---
发件人: "CarOL"<notifications@github.com&gt;
发送时间: 2021年2月28日(周日) 晚上6:23
收件人: "hx-w/CSGOWiki-Plugins"<CSGOWiki-Plugins@noreply.github.com&gt;;
抄送: "anyongye"<3090874781@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题: Re: [hx-w/CSGOWiki-Plugins] 游戏内发送!qq 机器人群里会发生乱码 (#12)




 
关于qq里显示乱码的问题，我刚刚区别的服务器测了一下，也使用了中文+英文的名称，是正常显示的。
 也有其他用户是用的中文名，同样可以正常显示。
 所以我猜想可能和你服务器上装的其他插件有关，建议换英文名尝试一下。
 如果不介意的话 可以发一下服务器装有插件的列表

**Comment by hx-w** [comment]
#19
