### ISSUE TITLE
游戏内使用!wiki指令请求超时

### ISSUE THREAD

**Issue by anyongye** [hx-w/CSGOWiki-Plugins#13]
游戏内使用!wiki指令请求超时 等待后再次输入还是请求超时

**Comment by hx-w** [comment]
已查清是超出请求限制
v1.2.1版本增加了超出请求次数限制的提示。
参考：[不同等级的请求次数限制](https://www.csgowiki.top/profile/exp/)
最近网站改版，会适当增加请求次数限制。
