### ISSUE TITLE
In-game ADMIN menu support for this plugin

### ISSUE THREAD

**Issue by hx-w** [hx-w/CSGOWiki-Plugins#3]
是否需要提供插件的管理员菜单，功能可以包括：
1. 各个子功能的临时关闭与开启(换图后重置为cfg的设置)
2. 限制某个/某些玩家的请求次数
3. 禁止/允许某个玩家上传道具

可以有这两个方法：
1. 直接拓展`!admin`指令的菜单，增加csgowiki相关管理指令。不过这种方式应该只有`z`权限的管理员才能使用
2. 新增一个新的`b`权限管理员指令：`!wikiop`，用于处理相关事务。这种方式需要多记一个指令，看实际取舍

如果实现相关功能则需要数据库的支持：
- 选用何种数据库`sqlite`/`mysql`/`postgresql`？
- 安装操作难度如何把握？
- 是否应该做成可选？不安装数据库的话则不支持*限制某些玩家行为*的功能

**Comment by H0wAway** [comment]
1. sqlite，单纯因为系统自带。
2. 拓展`!admin`指令不懂是什么意思，是在admin.cfg里面加上sm指令吗？那和单开一个管理员指令列表有什么区别呢？
3. 我觉得禁止/允许某个玩家上传道具可以通过限制某个/某些玩家的请求次数为0的极端情况实现。

**Comment by hx-w** [comment]
> 1. sqlite，单纯因为系统自带。
> 2. 拓展`!admin`指令不懂是什么意思，是在admin.cfg里面加上sm指令吗？那和单开一个管理员指令列表有什么区别呢？
> 3. 我觉得禁止/允许某个玩家上传道具可以通过限制某个/某些玩家的请求次数为0的极端情况实现。

- 我觉得既然没有频繁数据库交互的需求，用sqlite比较方便。
- 拓展`!admin`是指丰富`!admin`指令呼出的菜单界面内容，我看到有文档说可以通过插件实现，不过我现在的想法是直接拓展管理员`!wiki`指令的功能，在`!wiki`菜单上多出几个权限选项。
- 插件里**道具上传`!submit`**和**道具请求`!wiki`**是分开的，有单独的开关，可能需要两个管理员用户权限：
    1. 禁止/允许某个用户上传道具
    2. 限制某个用户请求道具的次数

**Comment by H0wAway** [comment]
1. 我觉得你的想法很不错。
2. CarOL，yyds。

**Comment by hx-w** [comment]
#15
